openapi: 3.0.0
servers: []
info:
  description: This is an example API to demonstrate a possible bug. JSON is rendered well, but XML is not rendering all the examples, but just the first one.
  version: "2.0.0"
  title: Simple API
  contact:
    email: mwgrootwassink@tui.nl

paths:
  /books:
    get:
      tags:
        - command
      summary: searches books
      operationId: searchBooks
      description: |
        By passing in the appropriate options, you can search for
        available books in the system
      parameters:
        - in: query
          name: title
          required: false
          schema:
            type: string
        - in: query
          name: author
          required: false
          schema:
            type: string
        - in: query
          name: publisher
          required: false
          schema:
            type: string

      responses:
        '200':
          description: search results matching criteria
          content:
            application/xml:
              schema:
                type: array
                $ref: '#/components/schemas/Books'
          headers:
            X-TUI-EAI-Limit:
              $ref: '#/components/headers/X-TUI-EAI-Limit'
            X-TUI-EAI-NextOffsetLink:
              $ref: '#/components/headers/X-TUI-EAI-NextOffsetLink'
            X-TUI-EAI-Offset:
              $ref: '#/components/headers/X-TUI-EAI-Offset'
            X-TUI-EAI-TotalResults:
              $ref: '#/components/headers/X-TUI-EAI-TotalResults'                


components:
  schemas:
  
    Books:
      type: array
      xml:
        name: books
        wrapped: true
      items:
        $ref: '#/components/schemas/Book'
      example:
        - isbn: '9780099179511'
          title: The Chamber
          author: John Grisham
        - isbn: '9780385424738'
          title: The rainmaker
          author: John Grisham
        - isbn: '9780552149518'
          title: The Da Vinci Code
          author: Dan Brown

    Book:
      type: object
      xml:
        name: book
      properties:
        isbn:
          type: string
          format: uuid
        title:
          type: string
        author:
          type: string
          
  headers:
    X-TUI-EAI-Limit:
      description: Maximum number of responses in list. Equals to the query parameter
      schema:
        type: integer
        example: 100
    X-TUI-EAI-NextOffsetLink:
      description: Link to the next Offset of response objects
      schema:
        type: string
        example: 'http://eai.tui.com/Airports'
    X-TUI-EAI-Offset:
      description: The current Offset
      schema:
        type: integer
        example: 0
    X-TUI-EAI-TotalResults:
      description: Total results
      schema:
        type: integer
        example: 2
