swagger: '2.0'
info:
  title: test
  version: 1.0.0

paths:
  /:
    get:
      produces: 
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Users'

definitions:
  Users:
    type: array
    items:
      $ref: '#/definitions/User'
    xml:
      name: users
      wrapped: true
    example:
      - id: 1
        name: Arthur Dent
      - id: 2
        name: Ford Prefect
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
    xml:
      name: user
# Added by API Auto Mocking Plugin
host: dev-virtserver.swaggerhub.com
basePath: /danman5/testBug/1.0.0
schemes:
 - https
